const { GoogleSpreadsheet } = require('google-spreadsheet');
const {client_email, private_key} = require('dotenv').config().parsed;
const spreadsheetId = "1hc-vBP11g5JwygPvc3BN7ckNrDGiPC4OP2fY50-QinI";

async function sheets(){
    
// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet(spreadsheetId);

const creds = require('./keys.json'); // the file saved above
await doc.useServiceAccountAuth(creds);


// // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
// await doc.useServiceAccountAuth({
//   // env var values are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//   private_key: process.env.GOOGLE_PRIVATE_KEY,
// });

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
// await doc.updateProperties({ title: 'renamed doc' }); // updates document properties

const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
console.log(sheet.title);
console.log(sheet.rowCount);

// adding / removing sheets
const newSheet = await doc.addSheet({ title: 'hot new sheet!' });
await newSheet.delete();



}
sheets();